project:
  type: book
  output-dir: docs
  render:
    - "!interbranch.qmd"
    - "!code/"
    - "!replication-total"
    - "!archive/"
    - "!feedback/"
    - "!README"

book-content: true

book:
  title: "Unequal Invisible Representation"
  author: "Devin Judge-Lord, Eleanor Powell, Rochelle Snyder"
  date: today
  cover-image: assets/cover.png
  chapters:
     - index.md
     - acknowledgements.md
     - Chapter 1 - Intro.qmd
     - Chapter 2 - Theories of Interbranch Representation.qmd
     - Chapter 3 - Measuring (Invisible) Interbranch Representation.qmd
     - Chapter 4 - Unequal Interbranch Representation.qmd
     - Chapter 5 - Representing Individual Constituents.qmd
     - Chapter 6 - Representing Businesses.qmd
     - Chapter 7 - Representing Nonprofits and Local Governments.qmd
     - Chapter 8 - General Policy Work.qmd
     - Chapter 9 - Policy Work on Behalf of Business.qmd
     - Chapter 10 - Conclusion.qmd
     - references.md
  appendices:
     - Appendix.qmd
  search: true
  #repo-url: https://github.com/judgelord/cor-book
  downloads: pdf # [pdf, epub]

number-depth: 3

bibliography: assets/cor.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    number-depth: 2
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
  epub:
     cover-image: assets/cover.png

execute:
  echo: false
  cache: true
  message: false
  warning: false
