project:
  type: book
  output-dir: docs

book-content: true

book:
  title: "Unequal Invisible Representation"
  author: "Devin Judge-Lord, Eleanor Powell, Rochelle Snyder"
  date: today
  cover-image: cover.png
  chapters:
     - index.md
     - google_drive/Chapter 1 - Intro.md
     - google_drive/Chapter 2 - Theories of Interbranch Representation.md
     - google_drive/Chapter 3 - Measuring (Invisible) Interbranch Representation.md
     - google_drive/Chapter 4 - Unequal Interbranch Representation.md
     - google_drive/Chapter 5 - Representing Individual Constituents.md
     - google_drive/Chapter 6 - Representing Businesses.md
     - google_drive/Chapter 7 - Representing Nonprofits and Local Governments.md
     - google_drive/Chapter 8 - General Policy Work.md
     - google_drive/Chapter 9 - Policy Work on Behalf of Business.md
     - google_drive/Chapter 10 - Conclusion.md
     - references.qmd
  appendices:
     - google_drive/Appendix.md
  search: true
  #repo-url: https://github.com/judgelord/cor-book
  downloads: pdf # [pdf, epub]

number-depth: 3

bibliography: assets/congress.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    number-depth: 2
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
  epub:
     cover-image: cover.png
