project:
  type: book
  output-dir: docs

book:
  title: "Unequal Invisible Representation"
  #author: "Jane Doe"
  #date: "8/18/2021"
  cover-image: cover.png
  chapters:
     - index.md
     - Chapter 1 - Intro.md
     - Chapter 2 - Theory.md
     - Chapter 3 - Meta Empirics.md
     - Chapter 4 - Individual Constituency Service.md
     - Chapter 5 - Corporate Constituency Service.md
     - Chapter 6 - Nonprofit and Local Government Constituency Service.md
     - Chapter 7 - General Policy.md
     - Chapter 8 - Corporate Policy.md
     - Chapter 9 - Conclusion.md
     - references.qmd
  appendices:
     - Appendix A - Data and Methods.md
  search: true
  #repo-url: https://github.com/judgelord/cor-book
  downloads: pdf # [pdf, epub]

number-depth: 3

bibliography: assets/congress.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    number-depth: 2
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
  epub:
     cover-image: cover.png
