
# Disparities in Interbranch Representation {#sec-intro}


::: {.content-hidden unless-meta="book-content”}

> ABSTRACT: This chapter presents an overview of our argument and the following chapters. We introduce the concept of interbranch representation and the implications of highly unequal levels of interbranch representation for democracy.

:::

```{r knit-options, include=FALSE}
type = "total"
load(here::here("data", type, "means.Rdata"))

here::here("code", "formatting.R") |> source()
```


# Introduction

How well do Members of Congress represent their constituents? This seemingly simple question is one that political scientists return to again and again. We argue that a myopic focus on legislative work has limited contemporary understanding of congressional representation. In so doing, scholars have largely overlooked a significant component of the work of congressional offices: direct engagement with federal agencies. We have thus failed to assess our democracy on important grounds. 

In this paper, we advance and measure the concept of **interbranch representation** --- how Members of Congress work directly with federal agencies on behalf of various constituencies. Interbranch representation includes casework (constituency service) on behalf of individuals, nonprofits, and businesses as well as communicating with agencies about executive-branch policymaking and implementation.^[
As we note below, parts of this broader concept have been studied under labels including "congressional oversight," "constituency service" [@Fenno1978], "lettermarking" in the context of spending [@MillsKalafHughes2015], "lobbying," "backchannel representation," "backdoor lawmaking," or "policy representation" in the context of agency policymaking [@Ritchie2018; @Ritchie2023; @RitchieYou2019; @LauterbachRitchie2025], "legislator advocacy" in the context of both constituent and donor service [@PowellJudgeLordGrimmer2023], "interbranch representation" in the context of legislators advising agency working groups [@USDepartmentofJustice2016], and "interbranch representation of protected groups" in the context of descriptive representation in contacts to the bureaucracy [@LowandeRitchieLauterbach2019], or simply "representation" in the context of all types of requests to the bureaucracy [@JudgeLordPowellGrimmer2026]. We adopt "interbranch representation" as a general umbrella concept to describe all of these kinds of representational activities, not only working group participation or contacts on behalf of descriptive identities, but also work on behalf of any other constituency, donor, business, industry, or district opinion on policy issues.] 
For example, prior work shows how legislators engage in interbranch representation to represent constituents' needs [@Fiorina1977; @Fenno1978; @MillsKalafHughes2015; @PowellJudgeLordGrimmer2023; @SnyderJudgeLordPowellGrimmer2025], constituents' policy preferences [@Ritchie2018; @Ritchie2023], shared identity groups <small>[@LowandeRitchieLauterbach2019], corporate donors, or [@PowellJudgeLordGrimmer2023]. 

We advance a unified framework of Demand, Capacity, and Motivation to explain variation in interbranch representation, integrating and extending theories rooted in unequal demand, unequal legislator capacity, and varying strategic motivations to invest time and energy in interbranch representation as opposed to other activities like legislating, communications, or fundraising. 
Prior work has typically studied these activities --- and their explanations --- piecemeal, focusing on one type of activity and a narrower set of causes at a time. To explain variation in interbranch representation, studies have focused on institutional position [@Lowande2018APSR; @LowandePotter2021; @LauterbachRitchie2025; @JudgeLordPowellGrimmer2026], experience [@Ritchie2018; @Ritchie2023; @Lowande2018APSR; @JudgeLordPowellGrimmer2026], or party status and partisan alignment [@Ritchie2018; @Ritchie2023; @PowellJudgeLordGrimmer2023; @Lowande2018APSR; @Lowande2019; @LauterbachRitchie2025].
Theories also suggest that interbranch representation ought to be driven by ideological alignment and electoral competition [@Fiorina1977; @King1991], but these intuitions are largely unsupported by empirical work [@Lowande2018APSR; @Ritchie2018; @Ritchie2023]. 
Our aim in this paper is to integrate types of behavior and explanations to provide a more comprehensive assessment of the drivers of interbranch representation. 

To do so, we leverage new data on interbranch representation, including over half a million hand-coded requests from Members of Congress to federal agencies from 2007 to 2025. This painstakingly collected new dataset allows us to systematically measure representation in a new way. Importantly, our comprehensive data allow us to put various explanations side by side with respect to the *relative* impact they have on overall interbranch representation. 

<!-- PARAGRAPH ABOUT SUB-TYPES THAT WE DON'T LOOK AT IN THIS PAPER 

We conceptualize interbranch representation as varying along two dimensions: the constituency represented (individuals, businesses, nonprofits, or local governments) and the type of representational activity undertaken (constituency service or policy work). This yields five sub-types of interbranch representation: (1) constituency service work on behalf of individual constituents, (2) constituency service work on behalf of businesses, (3) constituency service work on behalf of local governments or nonprofits, (4) working directly with federal agencies on general policy issues, and (5) working directly with federal agencies on policy on behalf of specific industries. In this paper, we focus on the total interbranch representation (the sum of both types of representational activities on behalf of all types of constituencies).^[In our broader book project, we explore each of these individual activities at length. Our theory of Demand, Capacity, and Motivation also provides hypotheses to explain variation in our five sub-types of interbranch representation. We find that all types of constituents—individuals, nonprofits, local governments, and businesses—receive highly unequal levels of interbranch representation across districts. Interbranch policy work (e.g., commenting on proposed agency rules) is similarly unequal. Interestingly, the legislators who provide more constituency service are often the same ones who do more policy work. This is because all types of interbranch representation are largely driven by capacity. We think of the capacity and experience of elected officials affecting their ability to legislate, or (sometimes) to help Joe Voter, but that same capacity also affects whether local businesses will get help negotiating a permit or contract and whether a local government or university will get help securing a federal grant.]  
--> 

We show that Members of Congress make over a hundred thousand requests a year directly to executive-branch officials. Unconstrained by legislative agendas and party discipline [@Ritchie2023], interbranch representation allows all Members of Congress to directly shape the workings of government. However, we find that work is highly unequal --- some members engage in extensive interbranch representation, and others do almost none. 

We evaluate effects on both the overall volume and distribution of interbranch representation. Specifically, we focus on the contribution of various causes of variation to the inequality across legislators. For example, classic political science theory suggests that different electoral security may lead some members to do more than others. Theories about office capacity offer different explanations for inequality in interbranch representation across legislators. Previous studies all focus on explanations for individual-level variation, not the shape of the distribution across all members. 

<!--- FIXME THIS DOES NOT FIT WELL HERE
By refocusing attention on the bulk of the actual work done in legislators’ offices,^[Recent data on congressional office staffing [@CrossonFurnasLapiraBurgat2021; @CrossonKaslovsky2024data] suggest that approximately 40% are dedicated to constituency service. A significant share of the other 60% are also engaged in interbranch representation, such as oversight investigations, hearings, and working with agencies, executive-branch policymaking, or administrative support for both interbranch representation and legislating. Given that most federal policymaking today is made through agency rulemaking, it is reasonable to estimate that at least 10% of legislators’ policy-focused staff time is engaged in inter-branch representation.] We revisit core questions of political science: How should we understand the representative functions of Members of Congress? Empirically, what drives differences in representation? <!--How do we assess the quality of representation? How do the legislative and executive branches interact? Has it changed in recent years?
Specifically, this paper focuses on explaining unequal levels of interbranch representation.--> 

Overall, we find that all three components of our framework  (demand, capacity, and motivation) explain inequality in interbranch representation. Consistent with prior research on the significant role of congressional capacity in explaining aspects of legislative behavior [@AshworthBuenodeMesquita2006; @Ritchie2018; @LaPiraDrutmanKosar2020; @Ritchie2023; @CrossonFurnasLapiraBurgat2021; @CrossonKaslovsky2024data; @JudgeLordPowellGrimmer2026], we find that the largest share of the inequality in interbranch representation can be explained by legislator capacity, especially staff resources and the institutional knowledge that comes with experience in office. Specifically, experienced legislators who allocate more office staff to constituency service and less to communications provide more interbranch representation. 
<!--TODO, TEST THE RATIO OF CS and COMMS STAFF--> 

Strategic motivations like reelection are important but modest drivers of overall variation in interbranch representation. We find varying results for different aspects of strategic behavior. Consistent with @Lowande2018APSR, we find legislators disproportionately contact agencies that their committees oversee and do not find that interbranch representation is driven by ideological disagreement. On the contrary, we find that legislators are much more likely to contact agencies perceived as ideologically proximate. We find some evidence for theories that interbranch representation is reelection-motivated [@King1991] and a strategic substitute for legislating when one's party is out of power [@Ritchie2018; @Ritchie2023].  Previous studies show convincingly that backchannel policy-making representation shapes behavior with certain agencies. Our near census of interbranch representation allows us to assess the relative magnitude of these effects in explaining overall behavior. <!--TODO ADD A SENTENCE ABOUT THE EFFECTS--> 
While the effect of having a co-partisan president is consistently in the direction predicted by theories of interbranch representation that focus on the president allocating resources to co-partisans [@BerryBurdenHowell2010], presidential partisanship is not consistently a significant predictor of interbranch representation across models. However, as with earmarking in appropriations, we show that institutional power contributes to inequalities in interbranch representation. 

Understanding this variation provides insight into how Congress is and isn’t functioning, the causes of inequalities in representation, and how interbranch representation could be improved. 
