
# Theories of Interbranch Representation {#sec-theory}


::: {.content-hidden unless-meta="book-content"}

> ABSTRACT: Our theory explains unequal levels of interbranch representation by clarifying the implications of a “folk theory” of model representation as well as several strategic and ideology-driven behaviors. Under a “folk theory” of representation, only district characteristics and legislator capacity would explain inequalities. We also clarify how political science theories about reelection strategy, money in politics, partisanship, ideology, and policy interests produce additional explanations for unequal levels and distribution of interbranch representation.

:::


```{r, include=FALSE}
# Totals and means for this chapter at top of document
type = "total"
load(here::here("data", type, "means.Rdata"))

# formatting for tables and numbers
here::here("code", "formatting.R") |> source()
```

<!--Rochelle 6/12: need some kind of intro here where we provide an overview of the chapter and our concept of interbranch representation-->

## Forging a new concept of representation from disparate scholarship 

To date, constituency service, oversight, and representation have been addressed by separate literatures. Constituency service has mostly been explored as reelection-oriented behavior. Oversight scholarship is dominated by principal-agent models of control. Representation has mostly been studied with respect to demographics, votes on bills, and, at times, speeches. The concept of interbranch representation that we advance in this project unifies constituency service, oversight, and other behaviors within a broader conceptual and empirical framework. We conceptualize all interactions with the bureaucracy as a decision to allocate effort (staff and time) to different priorities representing different constituencies, constrained by capacity. This framework offers a way to study this form of representation systematically as a function of one’s constituencies, capacity, and priorities.

Unlike other, more visible forms of congressional representation that have been the subject of substantial scholarly inquiry (roll-call votes, legislative speech, and bill sponsorship), interbranch representation is largely invisible and more difficult to study. Congress has refused to disclose data on this aspect of its work. In recent years, however, scholars have begun to obtain snapshots of this work from federal agencies that are (unlike Congress) subject to the Freedom of Information Act (FOIA) disclosure requirements. Acquiring these data is difficult, but doing so has yielded important findings on distributive politics [@MillsKalafHughes2015], descriptive representation [@LowandeRitchieLauterbach2019], agency policymaking [@Ritchie2018, and @Ritchie2023], legislative effectiveness [@KalafHughes2023], and money in politics [@PowellJudgeLordGrimmer2023]. However, the lack of systematic data across all agencies has necessarily limited the range of questions that could be explored with these data. 

## Constituency service



## Interbranch Dynamics and Congressional Oversight 

In recent decades, scholarship on the interaction between the legislative and executive branches has revolved around the concepts of strategic delegation of policymaking authority and appropriation of funds on the front end [@Arnold1979; @EpsteinOHalloran1999; @KiewietMcCubbins1991] and oversight on the back end [@McCubbinsSchwartz1984]. As a concept, delegation focuses attention on principal-agent dynamics. Oversight scholarship also focuses on principal-agent relationships, with some recent work on descriptive representation [@Minta2011]. <!--TODO MORE ON OVERSIGHT LIT--> 

Interbranch representation is not about acts of delegation and appropriation, but there are parallels and overlaps. Delegation and appropriation occur through voting, and scholars have shown significant inequalities in who is represented in legislative voting [@Bartels2008; @Carnes2016; @Gilens2012]. Studies of delegation of policymaking authority focus on asymmetric incentives and information across institutions [@EpsteinOHalloran1999; @Fiorina1982;  @McCubbinsSchwartz1984]. Interbranch representation is often aimed at improving legislator information and attempting to shape policy post-delegation in ways that were not possible within the legislative process [@Ritchie2018; and @Ritchie2023]. Other classic studies of the relationship between Members of Congress and federal agencies focus on appropriations [@Arnold1979; @KiewietMcCubbins1991]. This includes the presidential pork [@BerryBurdenHowell2010] and earmarking. Whereas earmarks are (in theory) a feature of annual appropriations legislation, a parallel dynamic of Members of Congress making requests for their district occurs on a daily basis through interbranch representation. Indeed, when legislative earmarks were banned, legislators likely turned to interbranch representation activities, such as "lettermarking" [@MillsKalafHughes2015]. 



## Representation 

Representation is most often studied as the congruence between legislators’ roll-call votes and constituents’ policy preferences [e.g., @MillerStokes1963; @Clinton2006; @AnsolabehereJones2010], with congruence constituting normatively "good" representation and suggesting that legislators are responsive to their constituents’ preferences. Studies of other forms of representation also assess congruence between constituents and legislators. 
<!--TODO rephrase--> 
Work on descriptive representation has assessed responsiveness on the basis of key identities [e.g., @BowenClark2014; @Canon1999], including responsiveness through interbranch representation [@LowandeRitchieLauterbach2019].  Scholarship on representation and inequality has found that legislators are more responsive to donors [@Gilens2012] and less responsive to less influential constituency groups [@Miler2010] and the poor [@Miler2018]. For these commonly studied forms of representation, public voting records make it possible for scholars to measure congruence or responsiveness.

Over the last few decades, scholars have begun to evaluate other forms of representation, ranging from legislators’ speech [@Grimmer2013; @GrimmerWestwoodMessing2014] to evaluating legislative effectiveness as a measure of the "quality of representation" [@VoldenWiseman2014; @CasasDennyWilderson2019]. Constituency service, on the other hand, has been studied primarily as a means for legislators to win reelection [@Fiorina1977]. In this view, legislators’ responsiveness to constituent requests is not a form of representation but an electoral activity that also serves legislators. Only recently has quantitative scholarship begun to view constituency service as a form of representation [@Snyder2024]. A large number of field experiments have uncovered distortions in legislators’ responsiveness to constituents for the sharing of policy opinions [@ButlerDynes2016; @HendersonHertelFernandezMildenbergerStokes2023], requests for meetings with legislators [@KallaBroockman2016], and requests for constituency service [@ButlerBroockman2011; @Lajevardi2020; @GarciaSadhwani2023]. Most of these studies, however, have been conducted on state legislators, and their results may not be generalizable to Members of Congress. Moreover, writing back to a constituent may not be the same as taking more substantive actions, such as intervening with a federal agency, on their behalf. 

We build on and complement this literature on representation and responsiveness by documenting and explaining inequalities in interbranch representation, broadly construed, across all members of Congress, across all federal agencies, and across all forms of interbranch representation. Next we break down our concept of interbranch representation into its three key components -- its interbranch function, its role in representation, and its behind-the-scenes nature -- and explain how each of these elements influences our theory about inequalities in interbranch representation.

## Interbranch Activities

<!--Rochelle 6/11: my vision for this interbranch section is to lay out the literature on different types of interbranch activities and then talk about what it means for us to be looking at things like oversight + constituency service together (unlike most previous studies) but idk how coherent this overall point is-->

Activities involving interactions between branches of government are a necessary part of the American constitutional system of checks and balances. The shared lawmaking, war, appointment, and treaty powers of Congress and the president are the hallmarks of a system that Richard @Neustadt1991 described as "separated institutions sharing powers." Scholarship on the relationship between Congress and the president and Congress and the bureaucracy has long explored the tensions that arise from such a system. These tensions are most apparent in activities such as congressional oversight of the bureaucracy, congressional delegation of policymaking authority, appropriations, and, to a lesser extent, constituency service. The wealth of existing research on these interbranch activities has largely considered each of them separately; out concept of interbranch representation, on the other hand, examines these activities together, as they occur at least in part through Congress's contacts with the bureaucracy.

<!--Rochelle 6/8: need more here on other foundational studies in these areas-->

In recent decades, scholarship on interactions between the legislative and executive branches has focused on strategic delegation of policymaking authority and appropriation of funds [@Arnold1979; @EpsteinOHalloran1999; @KiewietMcCubbins1991] and oversight [@McCubbinsSchwartz1984]. As a concept, delegation pays particular attention to the principal-agent problem and how Congress balances the need to control policy outcomes with the benefits of delegating policymaking authority to experts in the bureaucracy. Although Congress has delegated significant power to the executive branch over the past century, there remain a number of methods through which Congress can exert influence over bureaucratic policy outcomes. @MacDonald2013 shows that limitation riders in appropriations legislation have allowed Congress to influence rules in the bureaucracy even as the power of the administrative state has expanded. 

<!--Rochelle 6/11: need to talk more about Molly's research and letter-marking research in the paragraph above-->

Although most previous research has cast constituency service primarily as an activity that helps members of Congress electorally [e.g. @CainFerejohnFiorina1987; @Fiorina1977], it also requires congressional offices to interact with the federal bureaucracy. Members of Congress -- or, more precisely, their staff -- contact federal agencies on behalf of their constituents to help resolve individual bureaucratic issues that constituents have brought to their attention. Through this process of hearing from constituents, congressional offices may become aware of broader problems plaguing the bureaucracy, allowing constituency service to function as a form of oversight. 

While interbranch representation encompasses many forms of oversight, it is broader than activities traditionally considered oversight (e.g., hearings, investigations, sanctions). A small share of congressional interactions with bureaucrats concern issues that rise to the level of hearings and investigations. The vast majority are interventions in the agency's day-to-day operations [see, e.g., @Lowande2018APSR; @LowandePotter2021]. Agencies are constantly engaged in maintaining their political coalitions and reputations [@Carpenter2001; @Carpenter2014], by, for example, tagging all incoming requests from members of Congress as "VIP" and implementing protocols for rapid responses. An interbranch representation perspective broadens the concept of oversight to encompass not only occasional hearings and oversight reports prompted by crises and scandals but also daily requests for information and comments on implementation.

Beyond broadening the concept of oversight, the nature of our data means that we are examining several different kinds of interbranch activities, including constituency service and policy work related to oversight or appropriations, simultaneously. Most other studies of interbranch activities, besides those that have used similar data [e.g. @Ritchie2018; @Ritchie2023; @LowandeRitchieLauterbach2019; @Lowande2019], have examined only one type of interbranch activity at a time. Placing multiple interbranch activities under one umbrella for analysis has implications for our theory and for our characterization of the interbranch component of interbranch representation. Because our concept of interbranch representation encompasses both oversight and constituency service, it cannot be characterized solely as either adversarial or cooperative behavior. As such, it is difficult to make normative claims about the volume of interbranch representation and what that volume says about relations between the legislative and executive branches. However, as we describe at greater length in the following section, interbranch representation is one way in which Congress works to fulfill its constitutional responsibilities. 


## Representation and Interbranch Activities

Beyond helping Congress achieve its goals of conducting oversight of the executive branch, interbranch activities can also function as a form of representation. Hanna Pitkin's (1967, 209) canonical definition of "representation" as legislators' "acting in the interest of the represented, in a manner responsive to them" can help to illuminate the specific representational dimension of interbranch representation. Constituency service is an obvious form of responsiveness, as congressional offices contact the federal bureaucracy in response to their constituents' requests for help. In addition to this literal responsiveness, constituency service can also function as a vehicle for descriptive representation [@LowandeRitchieLauterbach2019] and a way for constituents to feel heard by their government [@Snyder2024]. And although, as legislators caution their constituents, they may not be able to achieve a favorable resolution to their constituents' problems, the act of *attempting* to resolve these issues is clearly a way in which congressional offices act in their constituents' interests.

<!--Rochelle 6/8: probably some more about other types & understandings of representation here. also need to correctly format the Pitkin citation in the paragraph above-->

Constituency service is one of the oldest forms of representation, dating back to the earliest congresses when constituents sought assistance with Revolutionary War pensions [@Eckman2025]. It has been discussed as an important form of representation in canonical studies of Congress [@Fenno1978]. Yet it remains one of the least understood congressional activities. @CainFerejohnFiorina1987 began their seminal book *The Personal Vote: Constituency Service and Electoral Independence* by lamenting the lack of attention to constituency service in the empirical literature. Much of what we know empirically about constituency service still comes from their survey of legislators, legislative staff, and constituents, which is now more than 40 years old. For example, we have found no direct and recent quantitative test of the assertion in @King1991 that constituency service is related to the incumbency advantage or of patterns documented by Fenno 50 years ago, such as the effect of legislators inheriting offices from their predecessors [@Fenno1978].

Following from these definitions and understandings of representation and responsiveness, scholars have typically understood normatively "good" representation to consist of an alignment between legislators' actions and constituents' interests. The early but comprehensive study of "policy congruence" between legislators and constituents by @MillerStokes1963 has spawned a robust literature on policy representation. Despite the difficulties inherent in measuring constituents' preferences at the congressional district level, @Clinton2006 examines dyadic policy representation and finds little evidence that legislators are consistently responsive to constituents' preferences in their roll-call votes. At the level of collective representation, @AnsolabehereKuriwaki2025 show that Congress often fails to pass legislation that a majority of the public supports. A number of other studies [e.g. @Bartels2008; @Miler2010; @Miler2018] have found that legislators represent the policy interests of the wealthy and powerful over those of ordinary constituents, raising concerns about distortions in substantive representation. 

While scholars and observers generally agree on the definition of normatively good substantive representation, it is less obvious what normatively good constituency service work would look like for members of Congress. Recently, field experiments and audit studies [e.g. @ButlerBroockman2011] have identified patterns of discriminatory responsiveness to constituent communications, primarily among state legislators. However, it remains the case that legislators perform (and claim credit for) vastly different amounts of constituent casework, which suggests that responsiveness to existing levels of constituent demand is a primary criterion by which constituency service work should be judged.

Constituency service's function as a form of oversight, discussed above, raises questions about the normative dimensions of interbranch representation. If legislators are contacting the bureaucracy primarily to address problems that their constituents are experiencing, then *more* interbranch representation may not necessarily be desirable. However, there are two reasons why a greater volume of interbranch representation may not be normatively concerning. First, given the role that we expect legislator capacity to play in explaining inequalities in interbranch representation, more contacts with the bureaucracy may be more indicative of this capacity than of any problems with the bureaucracy per se. Second, and relatedly, legislators may be engaging in these contacts for strategic purposes, which would also minimize the role of bureaucratic issues in driving these inequalities in interbranch representation. Below, after explaining the third key characteristic of interbranch representation, we describe our theory of demand, capacity, and motivation and further discuss how each of these factors may illuminate additional normative concerns. 

## The Relative Invisibility of Interbranch Representation

<!--Rochelle 6/11: Devin's suggestion is that we probably don't need a separate section on the invisibility of interbranch representation in the theory chapter, and I think I agree (it might be better just woven into the previous sections), but I've included what I have so far for this section anyway-->

The primary characteristic of interbranch representation that sets it apart from other interbranch activities and other forms of representation is its largely invisible nature. Although legislators sometimes claim credit for constituency service and communicate publicly about letters they send to federal agencies about policy, the routinized and near-constant quality of this work is hidden from public view. Congress has refused to disclose data on this aspect of its work, which would involve making itself subject to the Freedom of Information Act (FOIA) as most federal agencies are.


 

<!-- MOVE TO INTRO OR CONCLUSION 
Studying constituency service alongside other forms of interbranch representation can allow us to better understand what trade-offs, if any, legislators may face when providing representation to constituents. 

<!--
## The "Folk Theory" of Model Representation

We seek to explain inequalities in interbranch representation by contrasting a "folk theory" of model representation with theories that account for legislators’ \textbf{strategic motivations and capacity}. One of the central elements of interbranch representation-- constituency service--is often assumed to be a core institutional function of congressional offices, as evidenced by the fact that district office staff continue to provide constituency service even when the congressional office is vacant due to the death or resignation of the legislator. This dynamic suggests that constituency service is an activity aptly described by the "logic of appropriateness" that characterizes bureaucracies [@MarchOlsen1989]. In this view, legislators and their staff provide service to constituents simply because it is understood to be a key part of their representational responsibilities. The intuition here is that staff understand their job to be responding to all constituent requests. This is what we call the \textbf{Naive Folk Theory}: 

\begin{hypothesis}[Naive Folk Theory: Proportional Representation]
\label{hyp:naivefolk} Interbranch representation is proportional to district population. 
House: no variation in interbranch representation. Senate: Interbranch representation proportional to state population. 
\end{hypothesis}

This naive folk theory would expect no variation in interbranch representation in the House, where all legislators represent roughly the same number of constituents. In the Senate, however, it would expect interbranch representation proportional to the number of constituents a Senator represents. In this naive folk theory world, legislators are simply responding to all constituents in an even and apolitical manner. Existing research, however, suggests that such a view of legislative behavior as non-strategic (and in the strong form unconstrained) may be inadequate. As discussed above, political scientists have long understood legislators’ behavior, including their provision of constituency service, to be strategic, particularly when it comes to helping legislators achieve reelection [e.g., @Mayhew1974;  @CainFerejohnFiorina1987; @Fiorina1977; @Fenno1973]. Other research dating from the 1970s and 1980s has largely supported this claim [@SerraCover1992; @SerraMoon1994], and more recent work suggests that legislators behave as though constituency service has electoral benefits [@DroppPeskowitz2012], just as senators tailor their communications based on their electoral concerns [@Grimmer2013]. We therefore expect that legislators’ interbranch representation activities will vary according to their motivations. For example, electoral security, with less electorally secure legislators engaging in more contact with the bureaucracy.

Two additional features of the "Naive Folk Theory" are also unrealistic. First, the model representatives envisioned by this "Naive Folk Theory" would be assumed to have similar levels of institutional capacity with which to serve their constituents and engage in interbranch representation. In practice, however, members of Congress differ when it comes to the resources and staff at their disposal to support this work. Similarly, in this "Naive Folk Theory" world, the model representatives would also represent constituents with similar demands to their representatives. Yet in the real world, we might expect constituent demands to vary across districts. 

--> 


## A Unified Framework: Unequal Demand, Unequal Capacity, and Strategic Motivations

<!--The "Naive Folk Theory" of model representatives is insufficient to explain variation and inequality in interbranch representation. If we observe variation in interbranch representation in the House and variation in interbranch representation after controlling for state population in the Senate, we need an alternative explanation. Here, we build on existing research to introduce an \textbf{Unequal Demand, Unequal Capacity and Strategic Motivation Theory of Interbranch Representation}.  <!--This theory builds on the "Naive Folk Theory" of \ref{hyp:naivefolk}, by considering unequal demand, but adds consideration of unequal capacity, and varying strategic motivations. --> 

We introduce a framework of Demand, Capacity, and Strategic Motivations to extend and unify theoretical ideas from disparate strands of scholarship on Congress and the Bureaucracy. Demand and capacity-related explanations focus on legislator offices as bureaucracies. Strategic explanations focus on legislators as politicians. In the following sections, we elaborate on each of these components of our framework. 

### Unequal Demand

One of the central elements of interbranch representation—constituency service–is often assumed to be a core institutional function of congressional offices, as evidenced by the fact that district office staff continue to provide constituency service even when the congressional office is vacant due to the death or resignation of the legislator. This dynamic suggests that constituency service is an activity aptly described by the "logic of appropriateness" that characterizes bureaucracies (March and Olsen 1989). Extending this idea to the realm of interbranch representation, legislators and their staff provide service to constituents simply because it is understood to be a key part of their representational responsibilities. The intuition here is that staff understand their job to be responding to all constituent requests. 

In this paper, we limit our consideration of unequal demand to the varying number of constituents that legislators represent, with a particular focus on the Senate, with the wide range of state populations that senators represent. Conceptually, we might imagine that constituent demand could vary for reasons other than population. Some constituents might have a greater need for help from the federal government. Many constituents may not know that they could seek help from the Members of Congress. Further complicating this picture is that legislators appear to use capacity to generate demand through advertising and informing their constituents about ways they can help--either for strategic reasons or just because they believe normatively it is the right thing for them to do.

\begin{hypothesis}[Proportional Representation]
\label{hyp:demand}
Legislators who represent more constituents will be associated with higher levels of interbranch representation. 
\end{hypothesis}

### Unequal Capacity 

We turn next to the \textbf{Capacity} component of our theory. We argue that how much interbranch representation legislators engage in is likely to be positively associated with the capacity of the legislator's office. The intuition here is that how much interbranch representation a legislator's office can provide is likely to vary by the amount of capacity a legislator's office has. Offices with greater capacity have the potential to provide more interbranch representation, and vice versa. We are building on four existing streams of capacity literature: 1) formal theory voter screening models that predict that as a legislator's capacity increases, they will increase their level of constituency service [@AshworthBuenodeMesquita2006], 2) empirical research that suggests low congressional capacity serves as a major constraint on Congress's work [@LaPiraDrutmanKosar2020], 3) empirical research that shows legislator capacity impacts backchannel (backdoor) policymaking--when legislators contact executive agencies attempting to influence policy [@Ritchie2018; @Ritchie2023] and 4) our prior research that shows that increases in congressional capacity can offset shifts in legislator priorities between policymaking and constituency service [@JudgeLordPowellGrimmer2026].

\begin{hypothesis}[Unequal Capacity]
\label{hyp:capacity}
Legislators office with more capacity will be associated with higher levels of interbranch representation. 
\end{hypothesis}

There are, however, several different aspects of capacity to consider. We've thus developed sub-hypotheses that capture these different components of Congressional capacity. 

**Capacity gained from legislator experience.** Like anyone starting a new job, legislators face start-up costs such as how to organize their office, develop efficient routines, and make connections. Empirical research on both policy work with executive agencies [@Ritchie2018; @Ritchie2023; @JudgeLordPowellGrimmer2026] and constituency service work with executive agencies [@JudgeLordPowellGrimmer2026] has shown that capacity gained from legislator experience is correlated with higher levels of interbranch representation. Thus, 

\begin{subhypothesis}[Capacity: Legislator Experience]
\label{hyp:capacity-experience}
Legislators with more experience will be associated with higher amounts of interbranch representation
\end{subhypothesis}

**Staff quantity.** Committee chairs direct committee staff in addition to their own personal staff. Empirical research shows that this additional staff capacity increases both policy work [@Ritchie2018; @Ritchie2023; @JudgeLordPowellGrimmer2026] and constituency service [@JudgeLordPowellGrimmer2026]. 

\begin{subhypothesis}[Capacity: Staff Quantity]
\label{hyp:capacity-staff}
Legislators with more staff will provide more interbranch representation. 
\end{subhypothesis}

\begin{subhypothesis}[Capacity: Staff Allocation]
\label{hyp:capacity-staff}
Legislators who allocate staff to constituency service will provide more interbranch representation. 
\end{subhypothesis}

**Staff quality.** @Cottle2022 finds that staff experience affects the productivity of legislative committees. Similarly, we might expect that members who inherit experienced staff from the previous representative of that state or district will have more capacity for interbranch representation. Because staff are much more likely to stay when the new representative of the same party, we use whether the former representative was of the same party as a proxy for staff quality. We expect this effect to be especially strong in offsetting the start-up costs of new members in their first two years, so we allow it to vary by legislator experience.

\begin{subhypothesis}[Capacity: Staff Quality]
\label{hyp:capacity-staff-quality}
Legislators with higher-quality staff will be associated with higher amounts of interbranch representation. 
\end{subhypothesis}


<!-- COMMENTING THIS OUT FOR NOW BECAUSE IT COMPLICATES PRESENTATION OF RESULTS
Selected quality: Selecting Higher Performers: Did you Survive a Close Election in a prior time period? Did you survive an election?

\begin{subhypothesis}[Capacity: Competitive Election Selected Higher Quality]
\label{hyp:capacity-quality}
Competitive elections select higher-quality legislators. Therefore, legislators who won competitive elections will be associated with higher amounts of interbranch representation. 
\end{subhypothesis}
---> 


### Strategic Motivation Theory

How much energy and staff time do legislators want to devote to interbranch representation as opposed to other tasks (legislating, communicating, etc.)? It may depend on what they are trying to accomplish. Beginning with @Fenno1973 and @Mayhew1974, a substantial body of legislative politics literature has explored the strategic motivations of members of Congress. We begin with a general hypothesis that legislators with different strategic motivations will be associated with different levels of interbranch representation. These varying strategic motivations could shape members' desire to engage in both the constituency service and policy components of interbranch representation. <!--Importantly, the "naive folk theory" of model representatives (to the extent that it holds) is only capable of speaking to the constituency service component of interbranch representation. It is also inadequate for explaining inequalities in interbranch representation involving policy. Here, too, legislators’ goals and strategic efforts are likely to be important.  --> 

\begin{hypothesis}[Strategic Motivation]
\label{hyp:motivation}
Legislators have different motivations: How much energy and effort the legislator wants to invest in interbranch representation as opposed to other tasks (legislating, fundraising, etc.).
\end{hypothesis}

**Reelection Motivation.** While it is difficult to directly measure a legislator's motivation, we can identify situations in which legislators are likely to prioritize certain goals or motivations. Perhaps the most widely recognized strategic motivation of legislators is reelection [e.g., @Mayhew1974; @CainFerejohnFiorina1987; @Fiorina1977; @Fenno1973]. As David Mayhew famously wrote in \textit{Congress: The Electoral Connection}, "[Reelection] has to be the \textit{proximate} goal of everyone, the goal that must be achieved over and over if other ends are to be entertained,"[@Mayhew1974]. Legislators motivated by electoral concerns might devote additional attention and resources to helping their constituents, so that those constituents will vote to reelect the legislator [@SerraCover1992; @SerraMoon1994; @DroppPeskowitz2012 ]. This expectation, however, is contrary to Ritchie's findings in \textit{Backdoor Lawmaking}, which showed no consistent relationship between electoral vulnerability and policy-work with federal agencies [@Ritchie2023]. 

\begin{subhypothesis}[Motivation: Re-election]
\label{hyp:motivation-election}
Legislators worried about reelection (from more vulnerable districts) will be associated with higher amounts of interbranch representation
\end{subhypothesis}

**Majority Status in Chamber Motivation Decreasing Interbranch Representation.** In her research on backdoor policymaking with federal agencies, Ritchie argues that legislators are most likely to turn to backchannel lawmaking by appealing directly to federal agencies when they face obstacles in the legislative process [@Ritchie2023]. Majority legislators encounter a much friendlier legislative environment, and are thus less likely than minority legislators to turn to backchannel policy appeals to bureaucratic agencies. 

\begin{subhypothesis}[Motivation: Majority Status in Chamber Less Interbranch]
\label{hyp:motivation-majority-more}
Legislators from the majority party will be associated with lower amounts of interbranch representation.  
\end{subhypothesis}

**President's Party Increasing Interbranch Representation.** Building on @BerryBurdenHowell2010's finding that Members of the President's party receive more federal spending in their districts, we hypothesize that Members of the president's party may engage in higher levels of interbranch representation. Our reasoning here is that, as the name implies, interbranch representation is at the nexus of the executive and legislative branches. While the behavior we're documenting in this paper is the legislative portion of that relationship (legislators reaching out to executive branch agencies), to actually be able to deliver results to their constituents, they need cooperation from the executive branch agencies. If legislators of the president's party think they are more likely to receive higher levels of cooperation from executive branch agencies, they may be motivated to attempt interbranch representation at higher rates. 

\begin{subhypothesis}[Motivation: President's Party More Interbranch]
\label{hyp:motivation-president-more}
Legislators from the President's party will be associated with higher amounts of interbranch representation.
\end{subhypothesis}

**President's Party Decreasing Interbranch Representation.** The other side of the coin, however, is that while members of the president's party might anticipate a friendlier reception from executive branch agencies controlled by a same-party president, members of the opposition party might have greater incentives to engage in oversight of an executive branch controlled by an opposing party's president. Similarly, we might anticipate constituents of opposition party legislators having more concerns or problems with agencies controlled by a president of a different party, who might prioritize different types of constituents or policies less hospitable to opposition party constituents. Lastly, Ritchie's argument that legislators turn to backdoor policymaking when they confront obstacles in the legislative process applies here, too. Faced with a president unlikely to support the legislative proposals of opposition legislators, Ritchie found that legislators were more likely to turn to backchannel policymaking [@Ritchie2023].

\begin{subhypothesis}[Motivation: President's Party Less Interbranch]
\label{hyp:motivation-president-less}
Legislators from the President's party will be associated with lower amounts of interbranch representation.
\end{subhypothesis}

**Committee Oversight.** Interbranch representation includes many forms of agency oversight. Only a small proportion of congressional-agency interactions rise to the levels of hearings and investigations. Instead, as @Lowande2018APSR and @LowandePotter2021 demonstrate, most legislative interventions happen in direct communication between legislators and agencies. Legislators who sit on congressional committees overseeing an agency are likely to engage in higher levels of interbranch representation with that agency. We think this relationship is likely to exist for two reasons. First, legislators are likely to be substantively interested in that policy area to have received a seat on that committee. Second, their responsibility as committee members may also lead them to engage in higher interbranch representation with agencies under the committee's jurisdiction.  

\begin{subhypothesis}[Motivation: Committee Oversight]
\label{hyp:oversight}
Legislators who sit on a congressional committee that oversees an agency will engage in higher amounts of interbranch representation with that agency.
\end{subhypothesis}

**Ideologically Proximate.** Legislators who share similar preferences with an agency (are ideologically proximate to the agency) might want to engage in more work with the agency. 

\begin{subhypothesis}[Motivation: Ideologically Proximate]
\label{hyp:ideologicallyproximate}
Legislators who are ideologically aligned with an agency will engage in higher amounts of interbranch representation with that agency.
\end{subhypothesis}


**Ideologically Distant.** A competing hypothesis would be that legislators who dislike what an agency does (are ideologically distant from the agency) would be likely to send more communications to the agency somewhat. The rationale here is analogous to seeking to oversee or investigate something a legislator dislikes. 

\begin{subhypothesis}[Motivation: Ideologically Distant]
\label{hyp:ideologicallydistant}
Legislators who are ideologically distant from an agency will engage in higher amounts of interbranch representation with that agency.
\end{subhypothesis}

