

## Who is represented and how? 

### Individual Constituency Service in the Context of Interbranch Representation 


In the prior three chapters, we examined what explains the unequal levels of constituency service that legislators provide to individuals in their district. District demand and, especially, legislator capacity explain a large share of the variation. We find that legislators’ experience in office is the primary driver of constituency service work. However, constituency service is not entirely free of partisan and ideological influences. While reelection does not seem to motivate constituency service, ideologically moderate members do perform more of this work. Overall, our analysis suggests that demand and capacity matter most for individual constituency service, with strategy appearing important in small but surprising ways. 

<!-- Ellie: Potential Block quote to include -->

Because individual constituency service is such a large portion of interbranch representation overall, many of the findings in this chapter are similar to those discussed in @sec-typetotal. However, it is worth highlighting differences before proceeding to our analyses of the other four types of interbranch representation in the following chapters. These differences can illuminate factors that may be especially important for policy work or constituency service on behalf of businesses and nonprofits and local governments.

Several measures of capacity that matter for interbranch representation overall have weaker or less consistent effects for individual constituency service, suggesting that (as hypothesized) institutional position matters more for other types of interbranch representation. Ideological distance between the legislator and the agency matters only in the overall models, implying that it will come into play for other types of interbranch representation as well. Interestingly, while spending on constituency service staff is not related to amounts of individual constituency service, it is related to interbranch representation overall. Another surprising difference involves particular measures of demand (government sector employees and college graduates), which matter more consistently in the models assessing interbranch representation generally than those assessing individual constituency service. The following chapters explore these factors further by testing our hypotheses for the other four types of interbranch representation, beginning with corporate constituency service.


### Legislator Advocacy on Behalf of Corporations

What explains unequal levels of constituency service on behalf of businesses? We find that selective elements of all parts of our Demand, Capacity, and Strategic Choice framework are related to the provision of corporate service. For Demand, we find that having more constituents and more demanding constituents are correlated with greater provision of corporate service.  For Capacity, we find that legislator experience is always correlated with greater provision of corporate service, and that reporting committee assignments and committee leadership positions are sometimes correlated with greater provision of corporate service. For Strategic Responses to the Political Environment, we find that in accordance with their pro-business ideological beliefs, Republicans consistently do more corporate service. We also find that ideologically extreme legislators consistently do less corporate service, and members of the president’s party who are more ideologically distant do more corporate service. We observe House Members who are electorally vulnerable doing more corporate service; these findings are limited to the cross-sectional models. Lastly, we find that corporate campaign contributions are correlated with greater corporate service in cross-sectional, but not within-legislator models. This pattern regarding corporate campaign contributions holds at both the aggregate level, looking at all corporate contributions and all corporate service, as well as within an Energy Sector case study.  


Overall, we find that selective elements of all parts of our Demand, Capacity, and Strategic Choice framework are related to the provision of corporate service. For Demand, we find that having more constituents and more demanding constituents are correlated with greater provision of corporate service. For Capacity, we find that legislator experience is always correlated with greater provision of corporate service, and that reporting committee assignments and committee leadership positions are sometimes correlated with greater provision of corporate service. 

For Strategic Responses to the Political Environment, we find that consistent with their pro-business ideological beliefs, Republicans consistently do more corporate service. We also find that ideologically extreme legislators consistently do less corporate service, and members of the president’s party who are more ideologically distant do more corporate service. We observe House Members who are electorally vulnerable doing more corporate service, though these findings are limited to the cross-sectional models. Lastly, we find that corporate campaign contributions are correlated with greater corporate service in cross-sectional, but not within-legislator models. This pattern regarding corporate campaign contributions holds at both the aggregate level, looking at all corporate contributions and all corporate service, as well as within an Energy Sector case study.  


### nonprofit organizations and local governments

Advocating on behalf of nonprofit organizations and local governments, particularly those seeking support for grants, is a distinctive type of constituency service. That distinctiveness is apparent in our findings about what explains levels of (and inequalities in) service on behalf of nonprofits and local governments. Staff are important for this kind of work, as they are for both individual and corporate constituency service. Where this form of constituency service diverges from the other two that we have considered is in its closer relationship with policy. The grants for which these organizations apply are often a key part of policy implementation, which means that legislators' partisanship and ideology matter more for how they approach this kind of work. Legislators do more of this work on behalf of nonprofits and local governments when they share the party of the president and when they are ideologically closer to an agency, suggesting that they see these expressions of support as a means of controlling policy implementation. At the same time, these grants make a measurable difference in the lives of the communities that legislators represent, making them a key component of constituency service. 


### Public interest Policy 


Differences in the amount of policy work legislators do are driven by the capacity gained through institutional positions. Like with all forms of constituency service, experience matters, independent of institutional positions of power, but institutional power drives differences in policy work to a degree much greater than any kind of constituency service. Unsurprisingly, being a committee chair, ranking member, or oversight committee member is an especially strong predictor of contacting an agency about policy. Legislators are more likely to work with agencies on policy when they are ideologically aligned, reflecting how policy work is not just traditional “oversight” investigations into wrongdoing, but also includes proactive information seeking during the drafting of legislation and follow-up to make sure legislative directions result in agency rules as envisioned by the legislators, and, most commonly, engaging in debates over executive-branch policymaking based on congressional authorizations from decades past. 


### Corporate Policy work 

Policy work on behalf of businesses, in some ways, looks like other policy work (chairs, ranking members, and oversight committee members do more). In other ways, it is distinctly more partisan; having a co-partisan president is a much stronger predictor.

Differences in the amount of policy work legislators do are driven by the capacity gained through institutional positions. Like with all forms of constituency service, experience matters, independent of institutional positions of power, but institutional power drives differences in policy work to a degree much greater than any kind of constituency service. Unsurprisingly, being a committee chair, ranking member, or oversight committee member is an especially strong predictor of contacting an agency about policy. Legislators are more likely to work with agencies on policy when they are ideologically aligned, reflecting how policy work is not just traditional “oversight” investigations into wrongdoing, but also includes proactive information seeking during the drafting of legislation and follow-up to make sure legislative directions result in agency rules as envisioned by the legislators, and, most commonly, engaging in debates over executive-branch policymaking based on congressional authorizations from decades past. 

We find that selective elements of all parts of our Demand, Capacity, and Strategic Choice framework are related to the provision of corporate service. For Demand, we find that only state population is correlated with the provision of corporate policy work. For Capacity, we find that legislator experience is always correlated with greater provision of corporate policy, and that reporting committee assignments and committee leadership positions are sometimes correlated with greater provision of corporate policy. 

For Strategic Responses to the Political Environment, we find that consistent with their pro-business ideological beliefs, Republicans consistently do more corporate policy work. We also find that ideologically extreme legislators consistently do less corporate policy work. Legislators who are more ideologically distant from an agency engage in more policy work with that agency. We find House Members who are electorally vulnerable doing less corporate policy work, which is the opposite of what we found in terms of corporate constituency service--though in both cases the findings are limited to the cross-sectional models. Lastly, we find that corporate campaign contributions are correlated with greater corporate policy work in cross-sectional, but not within-legislator models. This pattern regarding corporate campaign contributions holds at both the aggregate level, looking at all corporate contributions and all corporate policy work, as well as within an Energy Sector case study.  




