# Conclusion

> ABSTRACT: We conclude by looking prospectively at the future of interbranch representation. This includes exploring the policy implications of our findings for how interbranch representation can be improved as well as discussing how interbranch representation seems to be changing during the second Trump administration.

We find high levels of inequality in interbranch representation. A large share of this inequality can be explained by legislator capacity, especially staff resources and experience. We find evidence of strategic behavior, with strong evidence that legislators work with ideologically proximate agencies and those whose committees they oversee, but this behavior does not explain inequality. We find some evidence for theories that interbranch representation is reelection-motivated and a substitute for legislating when one's party is out of power. Because legislator capacity drives so much of the inequality we observe, capacity-focused reforms — larger staffs, stronger training, and better retention of experienced personnel — may offer a promising lever for more equitable interbranch representation.

A focus on interbranch representation adds important nuance to modern narratives about a broken Congress. Although Congress may be broken in many ways, one under-appreciated way in which Congress still works is through interbranch representation (at least for some districts). The First Amendment to the U.S. Constitution guarantees the right "to petition the Government for a redress of grievances." In practice, citizens’ most direct experience with the federal government is with federal agencies. When citizens have grievances or simply need help navigating the federal bureaucracy, they petition their elected representatives for help. Legislators, in turn, petition the government for redress, facilitating responsiveness from agencies.

Examining interbranch representation reshapes our understanding of how the legislative and executive interact. Our models of interbranch relations (both in public discourse and formal theory) are largely based on a formal, constitutionally prescribed division of legislative and executive functions. Thus, political scientists have focused on legislative bargaining, delegation of policymaking authority, and oversight hearings. This focus neglects the primary way legislators interact with the executive branch. While certainly operating in the shadow of formal oversight, lawmaking, and budgeting powers, interbranch representation mostly relies on norms, relationships, and softer forms of legitimacy. From an interbranch representation perspective, "separation of powers" is a misleading moniker. The behavior we document involves formal and informal mechanisms by which legislators influence how the executive branch makes and implements policy on a daily basis. There are a few executive branch activities that Members of Congress do not involve themselves in, and any lack of involvement is likely due to a lack of capacity rather than any formal separation of powers on paper. 
