## - Electoral Competitiveness

- Figures: `figs/[TYPE]/m-elect-[1:4].png`

```{r m-elect,  fig.show="hold", out.width="50%", fig.height=4.5, fig.cap= "Per Year",fig.subcap= c("Model 1: Cross Sectional","Model 2: Diff in Diff","Model 3: restricted Diff in Diff","Model 4: log Diff in Diff")}

# cross-sectional 
m_elect_cross <- fenegbin (perYear ~ 
                         competitive + competitive_primary +
                           chair + ranking_minority + prestige + oversight +  
                    experience + 
                    majority + presidents_party | Year_x_Agency,
                    cluster = "Legislator", 
           data = data_member)

if(testing){modelsummary::modelsummary(m_elect_cross, gof_omit = "R.*", coef_omit = coef_omit)}

coefplot(m_elect_cross, horiz = T, drop = "(Intercept)") 



# 2
m_elect_did <-fenegbin (perYear ~ 
                       competitive + competitive_primary +
                         chair + ranking_minority + prestige + oversight +  oversight +
                    experience + 
                    majority  | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",
           data = data_member)

if(testing){modelsummary::modelsummary(m_elect_did, gof_omit = "R.*", coef_omit = coef_omit)}

coefplot(m_elect_did, horiz = T, drop = ".theta") 


# 3
m_elect_2nd_cross <-fenegbin (perYear ~ 
                       competitive + competitive_primary + 
                         chair + ranking_minority + prestige + oversight +  
                    #experience + 
                    majority + presidents_party | Year_x_Agency, 
                    cluster = "Legislator", 
           data = data_member %>% filter(survive == 1))

if(testing){modelsummary::modelsummary(m_elect_2nd_cross, gof_omit = "R.*", coef_omit = coef_omit)}
coefplot(m_elect_2nd_cross, horiz = T, drop = ".theta") 


# 4
m_elect_2nd_did <-fenegbin (perYear ~
                          competitive + competitive_primary + 
                            chair + ranking_minority + prestige + oversight +
                    #experience +
                    majority + presidents_party | Year_x_Agency + Legislator_x_Agency,
                    cluster = "Legislator",
           data = data_member %>% filter(survive == 1))

if(testing){modelsummary::modelsummary(m_elect_2nd_did, gof_omit = "R.*", coef_omit = coef_omit)}

coefplot(m_elect_2nd_did, horiz = T, drop = ".theta")
```


### Table - Electoral 

```{r m-elect-models}
models_elect <- list(
  "(1)" = m_elect_cross,
  "(2)" = m_elect_did,
  "(3)" =  m_elect_2nd_cross,
 "(4)" = m_elect_2nd_did
)

rows <- tibble(
  term = c("Dependent Variable", 
           #"Majority",
           #"President's Party",
           "All Legislators", 
           "Served At Least 2nd Term"),
  `(1)` = c("Count", "X", ""),
  `(2)` =c("Count", "X", ""),
  `(3)` = c("Count","", "X"),
  `(4)` = c("Count", "", "X") 
)

# subset
attr(rows, 'position') <- c(0, 20,21,22,23)

# call coefs
attr(rows, 'position') <- c(0)



# HTML
modelsummary(models_elect, 
             title = "The Effect of Experience and District Competitiveness on Legislator Contacts", 
             notes = list("Robust standard errors in parentheses, clustered by legislator."))

beta_cross <- betas(m_elect_cross)
se_cross <- standard_errors(m_elect_cross)
beta_did <- betas(m_elect_did)
se_did <- standard_errors(m_elect_did)
```



### Modeled Effects - electoral - cross sectional 

```{r}
#| label: "m-elect-effect"
#| fig-cap: "figs/[TYPE]/m-elect-effect"
#| layout-ncol: 2
#| fig-height: 3.5
#| fig-width: 3.5
#| fig-subcap: 
#|   - "1"
#|   - "2"
#|   - "3"
#|   - "4"
#| out-width: "100%"
#| fig-show: "hold"

model <- m_elect_cross
data = data_member |> filter(year > 2007,  year < 2019)

plot_effect( 
  newdata = mutate(data, competitive = 0),
  effect = "Competitive general election"
  )

plot_effect( 
  newdata = mutate(data, competitive_primary = 0),
  effect = "Competitive primary election"
  )

plot_effect( 
  newdata = mutate(data, competitive = 0,
                            # oversight = 0,
                            # prestige = 0,
                            competitive_primary = 0),
  effect = "Total electoral competition effect"
  )
```

### Modeled Effects - electoral - diff in diff

```{r}
#| label: "m-elect-did-effect"
#| fig-cap: "figs/[TYPE]/m-elect-did-effect"
#| layout-ncol: 2
#| fig-height: 3.5
#| fig-width: 3.5
#| fig-subcap: 
#|   - "1"
#|   - "2"
#|   - "3"
#|   - "4"
#| out-width: "100%"
#| fig-show: "hold"

model <- m_elect_did
data = data_member #|> filter(year > 2007,  year < 2019)

plot_effect( 
  newdata = mutate(data, competitive = 0),
  effect = "Competitive general election\n(diff in diff)"
  )

plot_effect( 
  newdata = mutate(data, competitive_primary = 0),
  effect = "Competitive primary election\n(diff in diff)"
  )

plot_effect( 
  newdata = mutate(data, competitive = 0,
                            # oversight = 0,
                            # prestige = 0,
                            competitive_primary = 0),
  effect = "Total electoral competition\n(diff in diff)"
  )
```

