\clearpage

## - Ideology

- Figures: `figs/[TYPE]/m-ideo-[1:4].png`

```{r m-ideo,  fig.show="hold", out.width="50%", fig.height=4.5, fig.cap= "Per Year",fig.subcap= c("Model 1: Cross Sectional","Model 2: Diff in Diff","Model 3: restricted Diff in Diff","Model 4: log Diff in Diff")}

#FIXME Move to top
data_member %<>% mutate(abs_nominate_dim1 = abs(nominate_dim1))

# cross-sectional 
m_ideo_cross <- fenegbin (perYear ~ 
                         chair + ranking_minority + prestige + oversight +  
                    experience + 
                    majority + abs_nominate_dim1*presidents_party +  distance*presidents_party | Year_x_Agency,
                    cluster = "Legislator", 
           data = data_member)

if(testing){modelsummary::modelsummary(m_ideo_cross, gof_omit = "R.*", coef_omit = coef_omit)}

coefplot(m_ideo_cross, horiz = T, drop = "(Intercept)") 



# 2
m_ideo_did <-feglm (perYear ~ 
                        chair + ranking_minority + prestige + oversight + 
                    experience + 
                    majority  + abs_nominate_dim1*presidents_party +  distance*presidents_party | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",
                    # ALT vcov = hetero ~ ssc(cluster.adj = TRUE),
           data = data_member)


if(testing){modelsummary::modelsummary(m_ideo_did, gof_omit = "R.*", coef_omit = coef_omit)}

coefplot(m_ideo_did, horiz = T, drop = ".theta") 


# 3
m_ideo_2nd_cross <-fenegbin (perYear ~ 
                        chair + ranking_minority + prestige + oversight +  
                    #experience + 
                    majority +
                      abs_nominate_dim1*presidents_party +  distance*presidents_party | Year_x_Agency, 
                    cluster = "Legislator", 
           data = data_member %>% filter(survive == 1))

if(testing){modelsummary::modelsummary(m_ideo_2nd_cross, gof_omit = "R.*", coef_omit = coef_omit)}
coefplot(m_ideo_2nd_cross, horiz = T, drop = ".theta") 


# # 4
# m_ideo_2nd_did <-fenegbin (perYear ~
#                           distance + chair + ranking_minority + prestige + oversight +
#                       abs_nominate_dim1*presidents_party +  distance*presidents_party + 
#                     majority | Year_x_Agency + Legislator_x_Agency,
#                     cluster = "Legislator",
#            data = data_member %>% filter(survive == 1))
# 
# if(testing){modelsummary::modelsummary(m_ideo_2nd_did, gof_omit = "R.*", coef_omit = coef_omit)}
# 
# coefplot(m_ideo_2nd_did, horiz = T, drop = ".theta")
```


### Table - Ideology 

```{r m-ideo-models}
models_ideo <- list(
  "(1)" = m_ideo_cross,
  "(2)" = m_ideo_did,
  "(3)" =  m_ideo_2nd_cross
)

rows <- tibble(
  term = c("Dependent Variable", 
           "Majority",
           "President's Party",
           "All Legislators", 
           "Served At Least 2nd Term"),
  `(1)` = c("Count", "X", "X", "X", ""),
  `(2)` =c("Count", "X", "X", "X", ""),
  `(3)` = c("Count", "X","X","", "X")
)

rows <- tibble(
  term = c("Dependent Variable", 
           #"Majority",
           #"President's Party",
           "All Legislators", 
           "Served At Least 2nd Term"),
  `(1)` = c("Count", "X", ""),
  `(2)` =c("Count", "X", ""),
  `(3)` = c("Count","", "X")#,
  #`(4)` = c("Log(Count+1)", "X", "") 
)

# call coefs
attr(rows, 'position') <- c(0)

options(modelsummary_factory_default = 'kableExtra')


# HTML
modelsummary(models_ideo,
             title = "The Effect of Experience and District Competitiveness on Legislator Contacts", 
             notes = list("Robust standard errors in parentheses, clustered by legislator."))

beta_cross <- betas(m_ideo_cross)
se_cross <- standard_errors(m_ideo_cross)
```


### Narrative - Ideology

TODO 



### Predictions - Ideology

- Figures: `figs/[TYPE]/m-predicted-[1:4].png`


```{r m-ideo-predicted,  fig.show="hold", out.width="50%", fig.cap= "",  fig.subcap= c("Model 1: Cross Sectional","Model 1: Cross Sectional", "Model 2: Diff in Diff","Model 2: Diff in Diff")}
# predicted <- predictions(m_ideo_cross,
#                          newdata = values)
# 
# # Cross-sectional predictions
# predicted %>%
#     mutate(estimate = estimate*n_agency, #predicted*n_agency,
#          conf.high = conf.high*n_agency, conf.low = conf.low*n_agency) %>%  # std.error = std.error*n_agency) %>%
#   ggcompetitive() + 
#   labs(title = "Predicted per Year",        subtitle = "(Cross-Sectional)",
#        x = "",
#        y = "Predicted Per Year",
#        fill = "",
#        color = "",
#        shape = "") 
# 
# # by tenure
# predicted <- predictions(m_ideo_cross,
#                          newdata = values_tenure)
# 
# predicted %>%
#     mutate(estimate = estimate*n_agency, #predicted*n_agency,
#          conf.high = conf.high*n_agency, conf.low = conf.low*n_agency) %>%  # std.error = std.error*n_agency) %>%
# ggtenure() +
#   labs(title = "Predicted Per Year",        subtitle = "(Cross-Sectional)",
#        x = "Years Serving in Congress",
#        y = "Predicted Letters Per Year",
#        fill = "",
#        color = "",
#        shape = "") 
```



### Modeled Effects - ideology

```{r}
#| label: "m-ideo-effect"
#| fig-cap: "figs/[TYPE]/m-ideo-effect"
#| layout-ncol: 2
#| fig-height: 3.5
#| fig-width: 3.5
#| fig-subcap: 
#|   - "1"
#|   - "2"
#|   - "3"
#|   - "4"
#| out-width: "100%"
#| fig-show: "hold"

model <- m_ideo_cross 
data = data_member |> filter(year > 2007,  year < 2019)

plot_effect( 
  newdata = data |>  
    mutate(nominate_dim1 = 0) |>
    mutate(distance = abs(nominate_dim1 - agency_ideo)),
  effect = "Legislator ideology"
  )

plot_effect(
  newdata = data |>  
    mutate(agency_ideo = 0) |>  
    mutate(distance = abs(nominate_dim1 - agency_ideo)),
  effect = "Perceived agency ideology"
  )
```
