
## Demand

### Districts with the largest and smallest percent federal workers 

```{r}

data_member |> 
  distinct(percent_workers_federal, member_state, population_total) |>
  arrange(-percent_workers_federal) |> 
  kablebox()

data_member |> 
  distinct(percent_workers_federal, state, district_code, population_total) |>
  arrange(percent_workers_federal, state, district_code) |> 
  kablebox()
```

- Figures: `figs/[TYPE]/m-demand-[1:4].png`

```{r}
#| fig-show: "hold"
#| label: m-demand
#| out-width: "50%"
#| fig-height: 4.5
#| fig-cap: "Per Year"
#| fig-subcap: 
#|   - "Model 1: Cross Sectional"
#|   - "Model 2: Diff in Diff"
#|   - "Model 3: full Cross Sectional"
#|   - "Model 4: fill Diff in Diff"

# cross-sectional 
m_demand_cross <- fenegbin (perYear ~ 
                              #  population_m + 
                              percent_public_assistance_or_snap_households + 
                               percent_education_bachelor_or_higher + 
                               #percent_workers_federal + 
                               majority + party + 
                               presidents_party | 
                               Year_x_Agency,
                             cluster = "Legislator", 
                             data = data_member)

if(testing){modelsummary::modelsummary(m_demand_cross, gof_omit = "R.*", starts = T, coef_omit = coef_omit)}

coefplot(m_demand_cross, horiz = T, drop = "(Intercept)") 



# 2
m_demand_did <-fenegbin (perYear ~ 
                              # population_total_m + 
                           percent_public_assistance_or_snap_households + 
                               percent_education_bachelor_or_higher + 
                               # percent_workers_federal + 
                               majority  +
                            presidents_party  | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",
           data = data_member)

if(testing){modelsummary::modelsummary(m_demand_did, gof_omit = "R.*", coef_omit = coef_omit)}

coefplot(m_demand_did, horiz = T, drop = ".theta") 


# 3
m_demand_full_cross <-fenegbin (perYear ~ 
                                 #population_m + 
                               percent_public_assistance_or_snap_households + 
                               percent_education_bachelor_or_higher + 
                               # percent_workers_federal + 
                              chair + 
                             ranking_minority + 
                             prestige + 
                             oversight +  
                    experience + 
                    majority + party + presidents_party | Year_x_Agency, 
                    cluster = "Legislator", 
           data = data_member)

if(testing){modelsummary::modelsummary(m_demand_full_cross, gof_omit = "R.*", coef_omit = coef_omit)}
coefplot(m_demand_full_cross, horiz = T, drop = ".theta") 


# 4
m_demand_full_did <-fenegbin (perYear ~ 
                             #  population_total + 
                                percent_public_assistance_or_snap_households + 
                               percent_education_bachelor_or_higher + 
                               # percent_workers_federal + 
                              chair + 
                             ranking_minority + 
                             prestige + 
                             oversight +  
                    experience + 
                    majority + presidents_party | Year_x_Agency + Legislator_x_Agency,
                    cluster = "Legislator",
           data = data_member)

if(testing){modelsummary::modelsummary(m_demand_full_did, gof_omit = "R.*", coef_omit = coef_omit)}

coefplot(m_demand_full_did, horiz = T, drop = ".theta")
```


### Table - demand %

```{r m-demand-models}
models_demand <- list(
  "(1)" = m_demand_cross,
  "(2)" = m_demand_did,
  "(3)" =  m_demand_full_cross,
 "(4)" = m_demand_full_did
)

rows <- tibble(
  term = c("Dependent Variable"),
  `(1)` = c("Count"),
  `(2)` =c("Count"),
  `(3)` = c("Count"),
  `(4)` = c("Count") 
)

# call coefs
attr(rows, 'position') <- c(0)

# HTML
modelsummary(models_demand, 
             title = "", 
             notes = list("Robust standard errors in parentheses, clustered by legislator."))

beta_cross <- betas(m_demand_cross)
se_cross <- standard_errors(m_demand_cross)
beta_did <- betas(m_demand_did)
se_did <- standard_errors(m_demand_did)

```


### Narrative - demand %

TODO


### Modeled Effects - demand- cross sectional 

```{r}
#| label: "m-demand-effect"
#| fig-cap: "figs/[TYPE]/m-demand-effect"
#| layout-ncol: 2
#| fig-height: 3.5
#| fig-width: 3.5
#| fig-subcap: 
#|   - "1"
#|   - "2"
#| out-width: "100%"
#| fig-show: "hold"

model <- m_demand_cross
data = data_member |> filter(year > 2007,  year < 2019)

plot_effect( 
  newdata = mutate(data, percent_education_bachelor_or_higher = 0),
  effect = "% College Grads"
  )
```

### Modeled Effects - demand- diff in diff

```{r}
#| label: "m-demand-did-effect"
#| fig-cap: "figs/[TYPE]/m-demand-did-effect"
#| layout-ncol: 2
#| fig-height: 3.5
#| fig-width: 3.5
#| fig-subcap: 
#|   - "1"
#| out-width: "100%"
#| fig-show: "hold"

model <- m_demand_did
data = data_member |> filter(year > 2007,  year < 2019)

plot_effect( 
  newdata = mutate(data, percent_education_bachelor_or_higher = 0),
  effect = "% College Grads\n(diff in diff)"
  )
```

