## - General Election Competitiveness

- Figures: `figs/[TYPE]/m-elect_basic-[1:4].png`

```{r}
#| label: m-elect_basic
#| fig-show: hold
#| out-width: 50%
#| fig-height: 4.5
#| fig-cap: "Per Year"
#| fig-subcap:
#|   - "Model 1: Cross Sectional"
#|   - "Model 2: Diff in Diff"
#|   - "Model 3: restricted Diff in Diff"
#|   - "Model 4: log Diff in Diff"

# cross-sectional 
m_elect_basic_cross <- fenegbin (perYear ~competitive | Year_x_Agency,
                    cluster = "Legislator", data = data_member)

# did
m_elect_basic_did <-fenegbin (perYear ~  competitive | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",  data = data_member)

# cross-sectional 
m_elect_basic_primary_cross <- fenegbin (perYear ~competitive + competitive_primary | Year_x_Agency,
                    cluster = "Legislator", data = data_member)

# did
m_elect_basic_primary_did <-fenegbin (perYear ~  competitive + competitive_primary | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",  data = data_member)

```


### Table - General 

```{r m-elect_basic-models}
models_elect_basic <- list(
  "(1)" = m_elect_basic_cross,
  "(2)" = m_elect_basic_did,
  "(3)" =  m_elect_basic_primary_cross,
  "(4)" = m_elect_basic_primary_did
)

rows <- tibble(
  term = c("Dependent Variable", 
           #"Majority",
           #"President's Party",
           "All Legislators", 
           "House Only"),
  `(1)` = c("Count", "X", ""),
  `(2)` =c("Count", "X", ""),
  `(3)` = c("Count","", "X"),
  `(4)` = c("Count", "", "X") 
)


attr(rows, 'position') <- c(0)

# HTML
modelsummary(models_elect_basic, 
             title = "The Effect of District Competitiveness and Ideology on Legislator Contacts", 
             notes = list("Robust standard errors in parentheses, clustered by legislator."))

beta_cross <- betas(m_elect_basic_cross)
se_cross <- standard_errors(m_elect_basic_cross)
beta_did <- betas(m_elect_basic_did)
se_did <- standard_errors(m_elect_basic_did)
```



### Modeled Effects - cross sectional 

```{r}
#| label: "m-elect_basic-effect"
#| fig-cap: "figs/[TYPE]/m-elect_basic-effect"
#| layout-ncol: 2
#| fig-height: 3.5
#| fig-width: 3.5
#| fig-subcap: 
#|   - "1"
#|   - "2"
#|   - "3"
#|   - "4"
#| out-width: "100%"
#| fig-show: "hold"

model <- m_elect_basic_cross
data = data_member |> filter(year > 2007,  year < 2019)

plot_effect( 
  newdata = mutate(data, competitive = 0),
  effect = "Competitive general election"
)

```

### Modeled Effects - elect_basicoral - diff in diff

```{r}
#| label: "m-elect_basic-did-effect"
#| fig-cap: "figs/[TYPE]/m-elect_basic-did-effect"
#| layout-ncol: 2
#| fig-height: 3.5
#| fig-width: 3.5
#| fig-subcap: 
#|   - "1"
#|   - "2"
#|   - "3"
#|   - "4"
#| out-width: "100%"
#| fig-show: "hold"

model <- m_elect_basic_primary_cross
data = data_member |> filter(year > 2007,  year < 2019)

plot_effect( 
  newdata = mutate(data, competitive_primary = 0),
  effect = "Competitive primary election"
)

```

