
## House staff spending - cross 

m_full_house_staff_spending_cross

```{r m_full_house_staff_spending_cross}

m_full_house_staff_spending_cross <- fenegbin (
  perYear ~ est_staff_spending + 
    population_m + 
     percent_workers_government + 
     percent_education_bachelor_or_higher + 
     percent_public_assistance_or_snap_households + 
    # percent_workers_self_employed + 
    # percent_workers_private_sector + 
    # percent_workers_nonprofit + 
    # electoral 
    competitive + 
    competitive_primary + 
    #PACamount_m + 
    # institution
    chair + 
    subchr + 
    ranking_minority + 
    #prestige + 
    oversight +  
    # member level 
    state_leg + 
    experience + 
     abs(nominate_dim1) + 
     party + 
    distance*presidents_party #+ majority 
  | Year_x_Agency, 
                    cluster = "Legislator",
           data = data_member |> filter(chamber == "House") )

if(testing){modelsummary::modelsummary(m_full_house_staff_spending_cross, stars = T)}
```




## House staff spending did

m_full_house_staff_spending_did

```{r m_full_house_staff_spending_did}
# controlling for expiernce 
m_full_house_staff_spending_did <-fenegbin (
  perYear ~ est_staff_spending + 
    # lots of this does not vary enough for the dif in diff 
    #population_m + 
      percent_workers_government + # model failing to converge dropping 
      percent_education_bachelor_or_higher + # model failing to converge dropping 
      percent_public_assistance_or_snap_households +  # model failing to converge dropping 
    # percent_workers_self_employed + 
    # percent_workers_private_sector + 
    # percent_workers_nonprofit + 
    # electoral 
     competitive + 
    competitive_primary + 
    #PACamount_m + 
    # institution
    chair +
    subchr +
    ranking_minority +
    # prestige + 
    oversight +  
    # member level 
    # state_leg + 
    experience + 
    # abs(nominate_1)
    # party + 
    # distance*presidents_party + 
    presidents_party #+ majority 
  | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",
           data = data_member |> filter(chamber == "House") )

if(testing){modelsummary::modelsummary(m_full_house_staff_spending_did, stars = T)}


```


## "models_full_staff_spending.Rdata"

```{r models_full_staff_spending}
models_full_staff_spending <- list(
  "(3)" =  m_full_house_staff_spending_cross,
  "(4)" = m_full_house_staff_spending_did
)

rows <- tibble(
  term = c("Dependent variable", 
           "All legislators", 
           "Only House",
           "Only Senate"),
  `(3)` = c("Count", "", "X", ""),
  `(4)` = c("Count", "", "X", "")
  )

attr(rows, 'position') <- c(0)

type 

# load(here::here("models", type, "models_full.Rdata")))
modelsummary(models_full_staff_spending) |> 
  group_tt(i = list(
    "Demand"= 2,
    "Political Environment" = 10,
    "Political Environment & Capcacy" = 26,
    "Capacity" = 28
  )) |> 
  style_tt(i = 44, line = "t", line_color = "black", line_width = 0.2) |>
  style_tt("groupi", background = "grey") |>
  style_tt("~groupi", j = 1, indent = 2)

beta_did <- betas(m_full_house_staff_spending_did)
se_did <- standard_errors(m_full_house_staff_spending_did)
beta_cross <- betas(m_full_house_staff_spending_cross)
se_cross <- standard_errors(m_full_house_staff_spending_cross)

save(models_full_staff_spending, rows, cm, gm,   beta_cross, beta_did, se_cross, se_did,
     file = here::here("models", type, "models_full_staff_spending.Rdata"))
```
