## Pooled House and Senate

m_full_cross

```{r m_full_cross}
# controlling for member - level 
m_full_cross <-fenegbin (
  perYear ~ 
    population_m + 
    chamber + 
    #workers_self_employed + 
    # workers_private_sector + 
    # workers_nonprofit + 
     percent_workers_government + 
     percent_education_bachelor_or_higher + 
     percent_public_assistance_or_snap_households + 
    # percent_workers_self_employed + 
    # percent_workers_private_sector + 
    # percent_workers_nonprofit + 
    # electoral 
    competitive + 
    #PACamount_m + 
    # institution
    chair + 
    subchr + 
    ranking_minority + 
    #prestige + 
    oversight +  
    # member level 
    state_leg + 
    experience + 
     abs(nominate_dim1) + 
     party + 
    distance*presidents_party #+ majority 
  | Year_x_Agency, 
                    cluster = "Legislator",
           data = data_member)

if(testing){modelsummary::modelsummary(m_full_cross, stars = T)}
```

## House

m_full_house_cross

```{r m_full_house_cross}

m_full_house_cross <- fenegbin (
  perYear ~ 
    population_m + 
     percent_workers_government + 
     percent_education_bachelor_or_higher + 
     percent_public_assistance_or_snap_households + 
    # percent_workers_self_employed + 
    # percent_workers_private_sector + 
    # percent_workers_nonprofit + 
    # electoral 
    competitive + 
    competitive_primary + 
    #PACamount_m + 
    # institution
    chair + 
    subchr + 
    ranking_minority + 
    #prestige + 
    oversight +  
    # member level 
    state_leg + 
    experience + 
     abs(nominate_dim1) + 
     party + 
    distance*presidents_party #+ majority 
  | Year_x_Agency, 
                    cluster = "Legislator",
           data = data_member |> filter(chamber == "House") )

if(testing){modelsummary::modelsummary(m_full_house_cross, stars = T)}
```

## Senate 

m_full_senate_cross 

```{r m_full_senate_cross}
m_full_senate_cross <-fenegbin (
  perYear ~ 
    population_m + 
     percent_workers_government + 
     percent_education_bachelor_or_higher + 
     percent_public_assistance_or_snap_households + 
    # percent_workers_self_employed + 
    # percent_workers_private_sector + 
    # percent_workers_nonprofit + 
    # electoral 
    competitive + 
    #PACamount_m + 
    # institution
    chair + 
    subchr + 
    ranking_minority + 
    #prestige + 
    oversight +  
    # member level 
    state_leg + 
    experience + 
     abs(nominate_dim1) + 
     party + 
    distance*presidents_party #+ majority 
  | Year_x_Agency, 
                    cluster = "Legislator",
           data = data_member |> filter(chamber == "Senate"))

if(testing){modelsummary::modelsummary(m_full_senate_cross, stars = T)}

```


## Full DID model for fixed effects 


## Pooled House and Senate

m_full_did

```{r m_full_did}
# controlling for member - level 
m_full_did <-fenegbin (
  perYear ~ 
    population_m + 
    chamber + 
     percent_workers_government + 
     percent_education_bachelor_or_higher + 
     percent_public_assistance_or_snap_households + 
    # percent_workers_self_employed + 
    # percent_workers_private_sector + 
    # percent_workers_nonprofit + 
    # electoral 
    competitive + 
    #PACamount_m + 
    # institution
    chair +
    subchr +
    ranking_minority +
    # prestige + 
    oversight +  
    # member level 
    # state_leg + 
    experience + 
    # abs(nominate_1)
    # party + 
    # distance*presidents_party + 
    presidents_party #+ majority 
  | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",
           data = data_member)

if(testing){modelsummary::modelsummary(m_full_did, stars = T)}


fixedEffects <- fixef(m_full_did)

fes <- tibble(
  fe = fixedEffects$Legislator_x_Agency,
  icpsr = names(fixedEffects$Legislator_x_Agency) |> str_remove(".*_") |> as.numeric()
) |> 
  group_by(icpsr) |> 
  summarise(fe = sum(fe) |> round() ) |> 
  left_join(member_data |> 
              distinct(icpsr, member_state, district_code)) |> 
  mutate(legislator = member_state |> 
           str_replace(".$", paste0("-", district_code, ")")) |> 
           str_replace("-0\\)", ")")
         ) |> 
  distinct(legislator, fe)

# top 
fes |> 
  arrange(-fe) |> 
  kablebox()

# bottom
fes |> 
  arrange(fe) |> 
  kablebox()

fes |> 
  ungroup() |> 
  ggplot() + 
  aes(
    y = reorder(legislator, fe), 
    x = fe,
    label = legislator
  ) + 
  geom_point(color = "grey") +
  geom_text(check_overlap = T, hjust = "inward", vjust = "inward") + 
  # geom_text_repel() + 
  theme_minimal() + 
  theme(axis.text.y = element_blank() ) + 
  labs( x = "Fixed Effect",
        y = "Legislator") 


fe_combined <- fes

save(fe_combined, file = here::here("data", "derived", "fe-combined.rds"))
```

## House

m_full_house_did

```{r m_full_house_did}
# controlling for expiernce 
m_full_house_did <-fenegbin (
  perYear ~ 
    # lots of this does not vary enough for the dif in diff 
    #population_m + 
      percent_workers_government + # model failing to converge dropping 
      percent_education_bachelor_or_higher + # model failing to converge dropping 
      percent_public_assistance_or_snap_households +  # model failing to converge dropping 
    # percent_workers_self_employed + 
    # percent_workers_private_sector + 
    # percent_workers_nonprofit + 
    # electoral 
     competitive + 
    competitive_primary + 
    #PACamount_m + 
    # institution
    chair +
    subchr +
    ranking_minority +
    # prestige + 
    oversight +  
    # member level 
    # state_leg + 
    experience + 
    # abs(nominate_1)
    # party + 
    # distance*presidents_party + 
    presidents_party #+ majority 
  | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",
           data = data_member |> filter(chamber == "House") )

if(testing){modelsummary::modelsummary(m_full_house_did, stars = T)}


fixedEffects <- fixef(m_full_did)

fes <- tibble(
  fe = fixedEffects$Legislator_x_Agency,
  icpsr = names(fixedEffects$Legislator_x_Agency) |> str_remove(".*_") |> as.numeric()
) |> 
  group_by(icpsr) |> 
  summarise(fe = sum(fe) |> round() ) |> 
  left_join(member_data |> 
              distinct(icpsr, member_state, district_code)) |> 
  mutate(legislator = member_state |> 
           str_replace(".$", paste0("-", district_code, ")")) |> 
           str_replace("-0\\)", ")")
         ) |> 
  distinct(legislator, fe)

# top 
fes |> 
  arrange(-fe) |> 
  kablebox()

# bottom
fes |> 
  arrange(fe) |> 
  kablebox()

# fes |> 
#   ungroup() |> 
#   ggplot() + 
#   aes(
#     y = reorder(legislator, fe), 
#     x = fe,
#     label = legislator
#   ) + 
#   geom_point(color = "grey") +
#   geom_text(check_overlap = T, hjust = "inward", vjust = "inward") + 
#   # geom_text_repel() + 
#   theme_minimal() + 
#   theme(axis.text.y = element_blank() ) + 
#   labs( x = "Fixed Effect",
#         y = "Legislator") 

fe_house <- fes

save(fe_house, file = here::here("data", "derived", "fe-house.rds"))
```

## Senate 

m_full_senate_did

```{r m_full_senate_did}

# controlling for member - level 
m_full_senate_did <-fenegbin (
  perYear ~ 
    population_m + 
    # chamber + 
    #workers_government +
    #education_bachelor_or_higher + 
    #public_assistance_or_snap_households + 
    #workers_self_employed + 
    # workers_private_sector + 
    # workers_nonprofit + 
     percent_workers_government + 
     percent_education_bachelor_or_higher + 
     percent_public_assistance_or_snap_households + 
    # percent_workers_self_employed + 
    # percent_workers_private_sector + 
    # percent_workers_nonprofit + 
    # electoral 
    competitive + 
    #PACamount_m + 
    # institution
    chair + 
    subchr + 
    ranking_minority + 
    # prestige + 
    oversight +  
    # member level 
    # state_leg + 
    experience + 
    # abs(nominate_1)
    # party + 
    # distance*presidents_party + 
    presidents_party #+ majority 
  | Year_x_Agency + Legislator_x_Agency, 
                    cluster = "Legislator",
           data = data_member |> filter(chamber == "Senate"))

if(testing){modelsummary::modelsummary(m_full_senate_did, stars = T)}


fixedEffects <- fixef(m_full_senate_did)

fes <- tibble(
  fe = fixedEffects$Legislator_x_Agency,
  icpsr = names(fixedEffects$Legislator_x_Agency) |> str_remove(".*_") |> as.numeric()
) |> 
  group_by(icpsr) |> 
  summarise(fe = sum(fe) |> round() ) |> 
  left_join(member_data |> 
              distinct(icpsr, member_state, district_code)) |> 
  mutate(legislator = member_state) |> 
  distinct(legislator, fe)

# top 
fes |> 
  arrange(-fe) |> 
  kablebox()

# bottom
fes |> 
  arrange(fe) |> 
  kablebox()

fe_senate <- fes

save(fe_senate, file = here::here("data", "derived", "fe-senate.rds"))
```


## "models_full.Rdata"

```{r models_full}
models_full <- list(
  "(1)" = m_full_cross,
  "(2)" = m_full_did,
  "(3)" =  m_full_house_cross,
  "(4)" = m_full_house_did,
  "(5)" = m_full_senate_cross,
  "(6)" = m_full_senate_did
)

rows <- tibble(
  term = c("Dependent variable", 
           "All legislators", 
           "Only House",
           "Only Senate"),
  `(1)` = c("Count", "X", "", ""),
  `(2)` = c("Count", "X", "", ""),
  `(3)` = c("Count", "", "X", ""),
  `(4)` = c("Count", "", "X", ""),
  `(5)` = c("Count", "", "", "X"),
  `(6)` = c("Count", "", "", "X")
  )

attr(rows, 'position') <- c(0)

# load(here::here("models", type, "models_full.Rdata")))
modelsummary(models_full) |> 
  group_tt(i = list(
    "Demand"= 2,
    "Political Environment" = 10,
    "Political Environment & Capcacy" = 26,
    "Capacity" = 28
  )) |> 
  style_tt(i = 44, line = "t", line_color = "black", line_width = 0.2) |>
  style_tt("groupi", background = "grey") |>
  style_tt("~groupi", j = 1, indent = 2)

beta_did <- betas(m_full_did)
se_did <- standard_errors(m_full_did)
beta_cross <- betas(m_full_cross)
se_cross <- standard_errors(m_full_cross)

save(models_full, rows, cm, gm,   beta_cross, beta_did, se_cross, se_did,
     file = here::here("models", type, "models_full.Rdata"))
```
